[WIP]: Add invidious.js connector
f1u77y/web-media-controller pull request #14
Opened 2019-04-07 22:09 UTC by doronbehar

Nothing really works yet, but instead of discussing it over at #13, it might be more comfortable here.

2019-04-07 22:19 UTC, f1u77y commented
Answering the questing from previous issue:

> One more question please regarding the mediaSelector: I tried to set it to just video with the hope that it will eventually make the playPause() functions work just like in YouTube but it didn't work.

`playPause()` uses `playButtonSelector`, so you might need set it for this function to work.

And I think you should add the js file name to the `directoryContents` variable just like other connectors. I know it's awful but I'll fix it later.

2019-04-07 22:24 UTC, doronbehar commented
> And I think you should add the js file name to the directoryContents variable just like other connectors. I know it's awful but I'll fix it later.

LOL I've managed to figure that out right before I read your comment :smile_cat:. That's available in https://github.com/f1u77y/web-media-controller/pull/14/commits/45c3d05b7d8981a8592c49442f8cf890834acccf

Actually, I think the PR is totally ready now. I've used both `mediaSelector` and `playButtonSelector` eventually.

2019-04-07 22:52 UTC, f1u77y requested changes

2019-04-07 22:52 UTC, f1u77y commented on connectors/invidious.js
> +        this.prefix = '/com/invidious';
This should be hostname in reverse order, eg. `/us/invidou`. Looks ugly but I think we should be consistent in prefix scheme.

2019-04-07 22:52 UTC, f1u77y commented on connectors/invidious.js
> +        const hasPrevButton = document.querySelector(this.prevButtonSelector) !== null;
There is no `prevButtonSelector` in your connector. Did you forget to remove this?

2019-04-07 22:52 UTC, f1u77y commented on connectors/invidious.js
> +            canGoPrevious: hasPrevButton,
I think `canGoPrevious` and `canGoNext` are always false unless this website has some kind of playlists.

2019-04-08 11:51 UTC, f1u77y commented
Seems fine now. Squash your commits please, and then I will merge.

2019-04-08 13:46 UTC, f1u77y approved these changes

2019-04-08 13:46 UTC, merged

2019-04-08 16:17 UTC, doronbehar commented
Thanks for the merge. Could you please add a new release? I thought I'd be able to build it my self but I get errors similar to the ones I reported in #13:

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "cws.json" file (Error code: ENOENT).

Running "build:firefox" (build) task

Running "clean:common" (clean) task
Verifying property clean.common exists in config...ERROR
>> Unable to process task.
Warning: Required config property "clean.common" missing. Use --force to continue.

Aborted due to warnings.
```