add soundcloud connector
f1u77y/web-media-controller pull request #24
Opened 2019-08-08 21:44 UTC by gutierri

2019-08-10 09:57 UTC, f1u77y commented
Thanks for your effort! 

As I can understand, `'.playbackSoundBadge .playbackSoundBadge__lightLink'` contains the user name info, which isn't always the artist name, while `'.playbackSoundBadge .playbackSoundBadge__titleLink span[aria-hidden=true]'` contains title and artist. So, I think it's better to split the latter into artist and title when possible and fallback to what are you doing now when not. You could see an implementation in a similar extension [here](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/soundcloud.js#L66).

Another issue (but it could be just on my side, so I'd like to ask if you encounter it too) is that extension sends something like "soundcloud.com - search everything" when the playback is paused. I'll try to look into that issue anyway.

The third issue is with album art. It's too small (50x50). I've tried to replace "50x50" with "200x200" and "500x500" in a few random art URLs and it worked, so please do it in this connector.

And just a cosmetic issue: you don't need that empty line 8 at the start of the constructor function.

All the other things about this connector seem fine.

2019-08-11 00:08 UTC, gutierri commented
I made the necessary adjustments. I created a method for bringing artist
and track information. See what you think of such a solution.

About the problem of sending "soundcloud.com - search everything", I did
not understand very well. Send to where? The problem I noticed now,
making corrections was that when the page is first loaded, it can't
start the track, it needs to be done manually. I am seeing how to solve.
Do you have this problem?


On 8/10/19 6:57 AM, Bogdan Sinitsyn wrote:
>
> Thanks for your effort!
>
> As I can understand, |'.playbackSoundBadge
> .playbackSoundBadge__lightLink'| contains the user name info, which
> isn't always the artist name, while |'.playbackSoundBadge
> .playbackSoundBadge__titleLink span[aria-hidden=true]'| contains title
> and artist. So, I think it's better to split the latter into artist
> and title when possible and fallback to what are you doing now when
> not. You could see an implementation in a similar extension here
> <https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/soundcloud.js#L66>.
>
> Another issue (but it could be just on my side, so I'd like to ask if
> you encounter it too) is that extension sends something like
> "soundcloud.com - search everything" when the playback is paused. I'll
> try to look into that issue anyway.
>
> The third issue is with album art. It's too small (50x50). I've tried
> to replace "50x50" with "200x200" and "500x500" in a few random art
> URLs and it worked, so please do it in this connector.
>
> And just a cosmetic issue: you don't need that empty line 8 at the
> start of the constructor function.
>
> All the other things about this connector seem fine.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/f1u77y/web-media-controller/pull/24?email_source=notifications&email_token=AAIPKPHQL4CN2BBGSB7QKYTQD2GJFA5CNFSM4IKOXADKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4AKKKA#issuecomment-520135976>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIPKPGHZAXUHH25HXTMQXDQD2GJFANCNFSM4IKOXADA>.
>

2019-08-15 21:37 UTC, f1u77y commented
> About the problem of sending "soundcloud.com - search everything", I did
not understand very well. Send to where?

To the background script from content script. Nevermind, I cannot reproduce it now.

> The problem I noticed now, making corrections was that when the page is first loaded, it can't start the track, it needs to be done manually. I am seeing how to solve. Do you have this problem?

I don't have the problem as for now.

2019-08-15 21:52 UTC, f1u77y requested changes

2019-08-15 21:52 UTC, f1u77y commented on connectors/soundcloud.js
> +    transform_track_to_artist() {
First of all, I use camelCase for functions and variables in the whole project, so I think it's better to follow the same code style across all of it.
Secondly, I think `transfrom_track_to_artist` isn't a good name for a method that returns `{artist, track}`. I'd consider something like `getArtistTrack()`.

2019-08-15 21:52 UTC, f1u77y commented on manifest.json
> +    }, {
Sorry, I've changed the extension layout a bit while this PR was pending. Now this info should be in `background/connectors.js`.

2019-08-16 17:37 UTC, gutierri commented
I made a push force and the necessary adjustments

On 8/15/19 6:37 PM, Bogdan Sinitsyn wrote:
>
>     About the problem of sending "soundcloud.com - search everything",
>     I did
>     not understand very well. Send to where?
>
> To the background script from content script. Nevermind, I cannot
> reproduce it now.
>
>     The problem I noticed now, making corrections was that when the
>     page is first loaded, it can't start the track, it needs to be
>     done manually. I am seeing how to solve. Do you have this problem?
>
> I don't have the problem as for now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/f1u77y/web-media-controller/pull/24?email_source=notifications&email_token=AAIPKPEHIXEE7BEY2AJTKMDQEXEAVA5CNFSM4IKOXADKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4NCF5Q#issuecomment-521806582>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIPKPFBACR4NHHCMJXJMA3QEXEAVANCNFSM4IKOXADA>.
>

2019-08-17 05:50 UTC, f1u77y approved these changes

2019-08-17 05:56 UTC, f1u77y commented
It's fine now but please resolve the conflicts.

2019-08-17 21:30 UTC, gutierri commented
Conflicts? It's all right here, and according to the github too!


Got it correct?


On 8/17/19 2:56 AM, Bogdan Sinitsyn wrote:
>
> It's fine now but please resolve the conflicts.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/f1u77y/web-media-controller/pull/24?email_source=notifications&email_token=AAIPKPG35ZCOKTWDAYQYHJDQE6HHPA5CNFSM4IKOXADKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4QEHKQ#issuecomment-522208170>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIPKPDPQ4QOCXTWPP3PWHTQE6HHPANCNFSM4IKOXADA>.
>

2019-08-18 17:19 UTC, merged